export const FIRMWARE_TYPE_UNKNOWN = '__UNKNOWN__',
  FIRMWARE_TYPE_BASEFLIGHT = 'BASEFLIGHT',
  FIRMWARE_TYPE_CLEANFLIGHT = 'CLEANFLIGHT',
  FIRMWARE_TYPE_BETAFLIGHT = 'BETAFLIGHT',
  FIRMWARE_TYPE_INAV = 'INAV';
