/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleImprintRouteImport } from './routes/$locale/imprint'
import { Route as LocaleDataPrivacyRouteImport } from './routes/$locale/data-privacy'
import { Route as LocaleToolsIndexRouteImport } from './routes/$locale/tools/index'
import { Route as LocaleGuidesIndexRouteImport } from './routes/$locale/guides/index'
import { Route as LocaleToolsDynamicIdleCalculatorRouteImport } from './routes/$locale/tools/dynamic-idle-calculator'
import { Route as LocaleToolsBlackboxAnalyzerRouteImport } from './routes/$locale/tools/blackbox-analyzer'
import { Route as LocaleGuidesGuideSlugRouteRouteImport } from './routes/$locale/guides/$guideSlug/route'
import { Route as LocaleGuidesGuideSlugIndexRouteImport } from './routes/$locale/guides/$guideSlug/index'
import { Route as LocaleGuidesGuideSlugStepSlugRouteImport } from './routes/$locale/guides/$guideSlug/$stepSlug'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleImprintRoute = LocaleImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDataPrivacyRoute = LocaleDataPrivacyRouteImport.update({
  id: '/data-privacy',
  path: '/data-privacy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleToolsIndexRoute = LocaleToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGuidesIndexRoute = LocaleGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleToolsDynamicIdleCalculatorRoute =
  LocaleToolsDynamicIdleCalculatorRouteImport.update({
    id: '/tools/dynamic-idle-calculator',
    path: '/tools/dynamic-idle-calculator',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleToolsBlackboxAnalyzerRoute =
  LocaleToolsBlackboxAnalyzerRouteImport.update({
    id: '/tools/blackbox-analyzer',
    path: '/tools/blackbox-analyzer',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleGuidesGuideSlugRouteRoute =
  LocaleGuidesGuideSlugRouteRouteImport.update({
    id: '/guides/$guideSlug',
    path: '/guides/$guideSlug',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleGuidesGuideSlugIndexRoute =
  LocaleGuidesGuideSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleGuidesGuideSlugRouteRoute,
  } as any)
const LocaleGuidesGuideSlugStepSlugRoute =
  LocaleGuidesGuideSlugStepSlugRouteImport.update({
    id: '/$stepSlug',
    path: '/$stepSlug',
    getParentRoute: () => LocaleGuidesGuideSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/404': typeof R404Route
  '/$locale/data-privacy': typeof LocaleDataPrivacyRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/guides/$guideSlug': typeof LocaleGuidesGuideSlugRouteRouteWithChildren
  '/$locale/tools/blackbox-analyzer': typeof LocaleToolsBlackboxAnalyzerRoute
  '/$locale/tools/dynamic-idle-calculator': typeof LocaleToolsDynamicIdleCalculatorRoute
  '/$locale/guides/': typeof LocaleGuidesIndexRoute
  '/$locale/tools/': typeof LocaleToolsIndexRoute
  '/$locale/guides/$guideSlug/$stepSlug': typeof LocaleGuidesGuideSlugStepSlugRoute
  '/$locale/guides/$guideSlug/': typeof LocaleGuidesGuideSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/$locale/data-privacy': typeof LocaleDataPrivacyRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/tools/blackbox-analyzer': typeof LocaleToolsBlackboxAnalyzerRoute
  '/$locale/tools/dynamic-idle-calculator': typeof LocaleToolsDynamicIdleCalculatorRoute
  '/$locale/guides': typeof LocaleGuidesIndexRoute
  '/$locale/tools': typeof LocaleToolsIndexRoute
  '/$locale/guides/$guideSlug/$stepSlug': typeof LocaleGuidesGuideSlugStepSlugRoute
  '/$locale/guides/$guideSlug': typeof LocaleGuidesGuideSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/404': typeof R404Route
  '/$locale/data-privacy': typeof LocaleDataPrivacyRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/guides/$guideSlug': typeof LocaleGuidesGuideSlugRouteRouteWithChildren
  '/$locale/tools/blackbox-analyzer': typeof LocaleToolsBlackboxAnalyzerRoute
  '/$locale/tools/dynamic-idle-calculator': typeof LocaleToolsDynamicIdleCalculatorRoute
  '/$locale/guides/': typeof LocaleGuidesIndexRoute
  '/$locale/tools/': typeof LocaleToolsIndexRoute
  '/$locale/guides/$guideSlug/$stepSlug': typeof LocaleGuidesGuideSlugStepSlugRoute
  '/$locale/guides/$guideSlug/': typeof LocaleGuidesGuideSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/404'
    | '/$locale/data-privacy'
    | '/$locale/imprint'
    | '/$locale/'
    | '/$locale/guides/$guideSlug'
    | '/$locale/tools/blackbox-analyzer'
    | '/$locale/tools/dynamic-idle-calculator'
    | '/$locale/guides/'
    | '/$locale/tools/'
    | '/$locale/guides/$guideSlug/$stepSlug'
    | '/$locale/guides/$guideSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/$locale/data-privacy'
    | '/$locale/imprint'
    | '/$locale'
    | '/$locale/tools/blackbox-analyzer'
    | '/$locale/tools/dynamic-idle-calculator'
    | '/$locale/guides'
    | '/$locale/tools'
    | '/$locale/guides/$guideSlug/$stepSlug'
    | '/$locale/guides/$guideSlug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/404'
    | '/$locale/data-privacy'
    | '/$locale/imprint'
    | '/$locale/'
    | '/$locale/guides/$guideSlug'
    | '/$locale/tools/blackbox-analyzer'
    | '/$locale/tools/dynamic-idle-calculator'
    | '/$locale/guides/'
    | '/$locale/tools/'
    | '/$locale/guides/$guideSlug/$stepSlug'
    | '/$locale/guides/$guideSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  R404Route: typeof R404Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/imprint': {
      id: '/$locale/imprint'
      path: '/imprint'
      fullPath: '/$locale/imprint'
      preLoaderRoute: typeof LocaleImprintRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/data-privacy': {
      id: '/$locale/data-privacy'
      path: '/data-privacy'
      fullPath: '/$locale/data-privacy'
      preLoaderRoute: typeof LocaleDataPrivacyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/tools/': {
      id: '/$locale/tools/'
      path: '/tools'
      fullPath: '/$locale/tools/'
      preLoaderRoute: typeof LocaleToolsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/guides/': {
      id: '/$locale/guides/'
      path: '/guides'
      fullPath: '/$locale/guides/'
      preLoaderRoute: typeof LocaleGuidesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/tools/dynamic-idle-calculator': {
      id: '/$locale/tools/dynamic-idle-calculator'
      path: '/tools/dynamic-idle-calculator'
      fullPath: '/$locale/tools/dynamic-idle-calculator'
      preLoaderRoute: typeof LocaleToolsDynamicIdleCalculatorRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/tools/blackbox-analyzer': {
      id: '/$locale/tools/blackbox-analyzer'
      path: '/tools/blackbox-analyzer'
      fullPath: '/$locale/tools/blackbox-analyzer'
      preLoaderRoute: typeof LocaleToolsBlackboxAnalyzerRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/guides/$guideSlug': {
      id: '/$locale/guides/$guideSlug'
      path: '/guides/$guideSlug'
      fullPath: '/$locale/guides/$guideSlug'
      preLoaderRoute: typeof LocaleGuidesGuideSlugRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/guides/$guideSlug/': {
      id: '/$locale/guides/$guideSlug/'
      path: '/'
      fullPath: '/$locale/guides/$guideSlug/'
      preLoaderRoute: typeof LocaleGuidesGuideSlugIndexRouteImport
      parentRoute: typeof LocaleGuidesGuideSlugRouteRoute
    }
    '/$locale/guides/$guideSlug/$stepSlug': {
      id: '/$locale/guides/$guideSlug/$stepSlug'
      path: '/$stepSlug'
      fullPath: '/$locale/guides/$guideSlug/$stepSlug'
      preLoaderRoute: typeof LocaleGuidesGuideSlugStepSlugRouteImport
      parentRoute: typeof LocaleGuidesGuideSlugRouteRoute
    }
  }
}

interface LocaleGuidesGuideSlugRouteRouteChildren {
  LocaleGuidesGuideSlugStepSlugRoute: typeof LocaleGuidesGuideSlugStepSlugRoute
  LocaleGuidesGuideSlugIndexRoute: typeof LocaleGuidesGuideSlugIndexRoute
}

const LocaleGuidesGuideSlugRouteRouteChildren: LocaleGuidesGuideSlugRouteRouteChildren =
  {
    LocaleGuidesGuideSlugStepSlugRoute: LocaleGuidesGuideSlugStepSlugRoute,
    LocaleGuidesGuideSlugIndexRoute: LocaleGuidesGuideSlugIndexRoute,
  }

const LocaleGuidesGuideSlugRouteRouteWithChildren =
  LocaleGuidesGuideSlugRouteRoute._addFileChildren(
    LocaleGuidesGuideSlugRouteRouteChildren,
  )

interface LocaleRouteRouteChildren {
  LocaleDataPrivacyRoute: typeof LocaleDataPrivacyRoute
  LocaleImprintRoute: typeof LocaleImprintRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleGuidesGuideSlugRouteRoute: typeof LocaleGuidesGuideSlugRouteRouteWithChildren
  LocaleToolsBlackboxAnalyzerRoute: typeof LocaleToolsBlackboxAnalyzerRoute
  LocaleToolsDynamicIdleCalculatorRoute: typeof LocaleToolsDynamicIdleCalculatorRoute
  LocaleGuidesIndexRoute: typeof LocaleGuidesIndexRoute
  LocaleToolsIndexRoute: typeof LocaleToolsIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleDataPrivacyRoute: LocaleDataPrivacyRoute,
  LocaleImprintRoute: LocaleImprintRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleGuidesGuideSlugRouteRoute: LocaleGuidesGuideSlugRouteRouteWithChildren,
  LocaleToolsBlackboxAnalyzerRoute: LocaleToolsBlackboxAnalyzerRoute,
  LocaleToolsDynamicIdleCalculatorRoute: LocaleToolsDynamicIdleCalculatorRoute,
  LocaleGuidesIndexRoute: LocaleGuidesIndexRoute,
  LocaleToolsIndexRoute: LocaleToolsIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  R404Route: R404Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
